### ISSUE TITLE
clang: error: no such file or directory: '../lib/.libs/libcurl.so'

### ISSUE THREAD

**Issue by liguangfa2008** [robertying/openssl-curl-android#1]
CC       curl-tool_xattr.o
  CC       ../lib/curl-strtoofft.o
  CC       ../lib/curl-nonblock.o
  CC       ../lib/curl-warnless.o
  CC       ../lib/curl-curl_ctype.o
  CCLD     curl
clang: error: no such file or directory: '../lib/.libs/libcurl.so'
make[2]: *** [curl] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

I get the error when I modify the script to build the libcurl.so
NDK use android-ndk-r19c
can anyone help?

**Comment by liguangfa2008** [comment]
the error just happen when I build for armv7a 
arm64 and x86 is ok

**Comment by robertying** [comment]
Hey! Could you please share the modified script?

**Comment by liguangfa2008** [comment]
just delete --disable-shared

**Comment by liguangfa2008** [comment]
you can delete other build phases, just leave armv7a build phase for testing

**Comment by robertying** [comment]
I reproduced the problem and did not find anything useful. It seems `libcurl.so` has never been built so it does not exist. Since it is ok on other architectures, I guess it's a problem with NDK arm toolchains.

You could probably try to convert the static lib to shared one... Or if you are also using `libcurl` for Android, NDK can generate `.so` file into `.apk` using static ones and it can work on Android.

**Comment by liguangfa2008** [comment]
yes，I also found that libcurl.so has never been built and also no useful log, may be it's a problem with NDK toolchains. thanks  ,I will try to link .o files into a .so file myself

**Comment by haolingyi** [comment]
I also have this problem solved by referring to the answer of this link
https://github.com/curl/curl/issues/4693

**Comment by xrparty** [comment]
**Solved:
Download android ndk-r22b or above from [here](https://developer.android.com/ndk/downloads/) ,  missing toolchains/llvm/prebuilt/darwin-x86_64/bin/ld at lower version of NDK**
